name: build-and-push-image

on:
  schedule:
    - cron: '32 16 * * *'
  push:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check if we have to do all this
        if: github.event_name != 'push'
        id: check
        uses: twiddler/is-my-docker-parent-image-out-of-date@fd8a50affce1f23efb83bd37647731cdb1143a0d
        with:
          parent-image: alpine:latest
          my-image: ghcr.io/marius/postfix-sendgrid

      - name: Checkout repository
        if: steps.check.outputs.out-of-date == 'true' || github.event_name == 'push'
        uses: actions/checkout@v2

      - name: Log into registry ${{ env.REGISTRY }}
        if: steps.check.outputs.out-of-date == 'true' || github.event_name == 'push'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        if: steps.check.outputs.out-of-date == 'true' || github.event_name == 'push'
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        if: steps.check.outputs.out-of-date == 'true' || github.event_name == 'push'
        id: build-and-push
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ghcr.io/marius/postfix-sendgrid:latest
          labels: ${{ steps.meta.outputs.labels }}
